---
project_name: malware
paths:
  model: ./models/malware_new/nn.model
  scaler: ./models/malware_new/scaler.joblib
misclassification_threshold: 0.5
norm: 2
initial_state_offset: 0
system:
  verbose: 1
save_history: "none"
