---
project_name: malware
paths:
  model: ./models/malware/baseline.model
  scaler: ./models/malware/baseline_scaler.joblib
  x_input: ./data/malware/baseline_X_test_candidates.npy
  y_input: ./data/malware/baseline_y_test_candidates.npy
dirs:
  results: ./out/attacks/malware/rq1/
n_input: -1
input_offset: 0
system:
  n_jobs: 10
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.9
norm: 2
