---
project_name: malware
paths:
  model: ./models/malware/baseline.model
  scaler: ./models/malware/baseline_scaler.joblib
  x_input: ./data/malware/baseline_X_test_candidates.npy
  y_input: ./data/malware/baseline_y_test_candidates.npy
dirs:
  results: /scratch/users/tsimonetto/my_test_out_r1_malware
n_input: -1
input_offset: 0
system:
  n_jobs: 100
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.9
norm: 2
