---
config_dir: ./config/
attacks:
#  - moeva
  - pgd
seeds:
  - 42
projects:
  - malware/rq1.malware.static
eps_list:
  - 0.1
budgets:
  - 10
loss_evaluations:
  - flip
#  - flip+sat
  - constraints+flip
  - constraints+flip+adaptive_eps_step
  - constraints+flip+adaptive_eps_step+repair