---
dirs:
  results: ./out/attacks/malware_new/training
paths:
  x_input: ./data/malware/X_test_candidates.npy
  y_input: ./data/malware/y_test_candidates.npy
input_offset: 0
n_input: 4
n_gen: 100
seed: 42