---
project_name: malware_rf
paths:
  model: ./models/malware_rf/baseline.model
  scaler: ./models/malware_rf/baseline_scaler.joblib
  x_input: ./data/malware_rf/baseline_X_train_candidates.npy
  y_input: ./data/malware_rf/baseline_y_train_candidates.npy
dirs:
  results: /scratch/users/tsimonetto/out_malware/papernot
n_input: -1
input_offset: 0
system:
  n_jobs: 100
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.9
norm: 2
