---
project_name: malware_rf_augmented
paths:
  model: ./models/malware_rf/augmented.model
  scaler: ./models/malware_rf/augmented_scaler.joblib
  x_input: ./data/malware_rf_augmented/augmented_X_train_candidates.npy
  y_input: ./data/malware_rf_augmented/augmented_y_train_candidates.npy
dirs:
  results: /scratch/users/tsimonetto/moeva_out/malware_rf/rq0.1
n_input: -1
input_offset: 0
system:
  n_jobs: 100
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.9
norm: 2
