---
config_dir: ./config/
models:
  - ./models/malware_rf/adv_moeva_full.model
attacks:
  # - moeva
  - papernot
seeds:
  - 42
projects:
  - malware_rf/rq2.malware_rf.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100