---
config_dir: ./config/
attacks:
  - moeva
seeds:
  - 42
projects:
  - malware_rf/rq4.malware_rf.static
  - malware_rf/rq4.malware_rf_augmented.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100
