---
project_name: malware_rf_augmented
paths:
  model: ./models/malware_rf/adv_moeva_augmented_rq4.model
  scaler: ./models/malware_rf/adv_moeva_augmented_rq4_scaler.joblib
  x_input: ./data/malware_rf_augmented/augmented_X_test_candidates.npy
  y_input: ./data/malware_rf_augmented/augmented_y_test_candidates.npy
dirs:
  results: ./out/attacks/malware_rf/rq4/
n_input: -1
input_offset: 0
system:
  n_jobs: 100
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.9
norm: 2
