---
projects:
  - malware_rf
overwrite: False
attack_classes:
  - 1
x_attacks:
 - name: moeva_rq4
   path: ./out/attacks/malware_rf/rq0/X_adv_moeva.npy
x_attacks_augmented: 
  - name: moeva_augmented_rq4
    path: ./out/attacks/malware_rf/rq0.1/X_adv_moeva.npy
distance: 0.05
norm: 2
classification_threshold: 0.9
