---
projects:
  - malware_rf
overwrite: False
attack_classes:
  - 1
x_attacks:
 - name: moeva_full
   path: ./out/attacks/malware_rf/rq0/X_adv_moeva.npy
#  - name: cpgd
#    path: ./out/attacks/url/rq0/x_attacks_pgd_constraints+flip+adaptive_eps_step_5c4d872a136dcf0f0c78f4fffac2375e.npy
distance: 0.05
norm: 2
classification_threshold: 0.9