---
config_dir: ./config/
attacks:
  - pgd
seeds:
  - 42
projects:
  - sm1.lcld.static
eps_list:
  - 0.025
  - 0.05
  - 0.1
  - 0.2
  - 0.4
budgets:
  - 500
  - 1000
  - 2000
loss_evaluations:
  - flip
  - flip+sat
  - constraints+flip
  - constraints+flip+adaptive_eps_step
  - constraints+flip+adaptive_eps_step+repair