---
config_dir: ./config/
models:
  - ./models/url/adv_moeva.model
  - ./models/url/adv_cpgd.model
attacks:
  - moeva
  - pgd
seeds:
  - 42
projects:
  - url/rq2.url.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100
loss_evaluations:
  - constraints+flip+adaptive_eps_step+repair