---
project_name: botnet_rf
paths:
  model: ./models/botnet_rf/baseline.model
  scaler: ./models/botnet_rf/baseline_scaler.joblib
  x_input: ./data/botnet_rf/baseline_X_test_candidates.npy
  y_input: ./data/botnet_rf/baseline_y_test_candidates.npy
dirs:
  results: ./out/attacks/botnet_rf/rq2/
n_input: -1
input_offset: 0
system:
  n_jobs: 128
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.5
norm: 2
