---
common:
  out_root: ./out/trying_all
  model: nn.model
  features: features.csv
  constraints: constraints.csv
  x_candidates: x_attack_candidates.npy
  min_max_scaler: scaler.joblib
  ml_scaler: scaler.joblib
  thresholds:
    f1: 0.25
    f2s:
      - 0.001
      - 0.005
      - 0.01
      - 0.031372549
      - 0.05
      - 0.1
  norm: inf
  initial_state_offset: 0
  n_initial_state: 1000
  seeds:
    - 0
  budget: 100000
  n_jobs: 1
  verbose: 1
  attacks:
    - name: 00_random
      objective_script:
    - name: 01_sat
      objective_script: 11_success_rate_numpy
    - name: 02_pgd
      objective_script: 11_success_rate_numpy
    - name: 04_moeva
      objective_script: 10_success_rate_results
      n_pop: 200
      n_offsprings: 100
      save_history: true
projects:
  - name: lcld
  - name: botnet