---
project_name: lcld
paths:
  model: ./models/botnet/nn.model
  features: ./data/botnet/features.csv
  constraints: ./data/botnet/constraints.csv
  x_candidates: ./data/botnet/x_attack_candidates.npy
  min_max_scaler: ./models/botnet/scaler.joblib
  ml_scaler: ./models/botnet/scaler.joblib
dirs:
  results: ./out/attacks/botnet/moeva/
misclassification_threshold: 0.5
norm: inf
n_initial_state: -1
initial_state_offset: 0
system:
  n_jobs: 14
  verbose: 1
save_history: true
budget: 100000
