---
project_name: botnet_augmented
paths:
  model: ./models/botnet_augmented/nn.model
  features: ./data/botnet_augmented/features.csv
  constraints: ./data/botnet_augmented/constraints.csv
  x_candidates: ./data/botnet_augmented/x_candidates_common.npy
  min_max_scaler: ./models/botnet_augmented/scaler.joblib
  ml_scaler: ./models/botnet_augmented/scaler.joblib
dirs:
  results: ./out/attacks/botnet_augmented/l2/
misclassification_threshold: 0.5
norm: 2
n_initial_state: -1
initial_state_offset: 0
system:
  n_jobs: 10
  verbose: 1
save_history: "reduced"
