---
config_dir: ./config/
attacks:
#  - moeva
  - pgd
seeds:
  - 42
projects:
  - lcld
#  - lcld_augmented
#  - botnet
#  - botnet_augmented
eps_list:
#  - 0.01
#  - 0.031
#  - 0.05
  - 0.1
#  - 0.2
#  - 0.3
#  - 0.5
budgets:
#  - 2000
  - 10000
#  - 1000
loss_evaluations:
  - flip
  - flip+sat
  - constraints+flip
  - constraints+flip+adaptive_eps_step
  - constraints+flip+adaptive_eps_step+repair