---
config_dir: ./config/
seeds:
  - 42
  - 2021
projects:
  - lcld
  - botnet
eps_list:
  - 0.01
  - 0.031
  - 0.1
budgets:
  - 10000
  - 100000
loss_evaluations:
  - flip
  - flip+sat
  - constraints+flip
  - constraints+flip+adaptive_eps_steps