---
project_name: lcld
paths:
  features: ./data/lcld/features.csv
  constraints: ./data/lcld/constraints.csv
  x_candidates: ./data/lcld/x_candidates_common_rq3.npy
  min_max_scaler: ./models/lcld/scaler.joblib
  ml_scaler: ./models/lcld/scaler.joblib
misclassification_threshold: 0.25
dirs:
  results: ./out/attacks/lcld/rq3/
norm: 2
n_initial_state: 4000
initial_state_offset: 0
system:
  n_jobs: 10
  verbose: 1
save_history: "full"
