---
project_name: lcld_augmented
paths:
  model: ./models/lcld_augmented/nn.model
  features: ./data/lcld_augmented/features.csv
  constraints: ./data/lcld_augmented/constraints.csv
  x_candidates: ./data/lcld_augmented/x_candidates_common.npy
  min_max_scaler: ./models/lcld_augmented/scaler.joblib
  ml_scaler: ./models/lcld_augmented/scaler.joblib
misclassification_threshold: 0.25
dirs:
  results: ./out/attacks/lcld_augmented/l2/
norm: 2
n_initial_state: 4000
initial_state_offset: 0
system:
  n_jobs: -1
  verbose: 1
save_history: "full"
