project_name: botnet
paths:
  features: ./data/botnet/features.csv
  constraints: ./data/botnet/constraints.csv
budget: 1000
n_pop: 200
n_offsprings: 100
save_history: "False"
seed: 42
system:
  n_jobs: 10
  verbose: 1
norm: 2
misclassification_threshold: 0.5
eps: 1.
loss_evaluation:  constraints+flip+adaptive_eps_step+repair
constraints_optim: sum
comet: True
attack_name: pgd