---
config_dir: ./config/
attacks:
#  - moeva
  - pgd
seeds:
  - 42
projects:
  - botnet
eps_list:
  - 1
budgets:
  - 1000
loss_evaluations:
#  - flip
#  - flip+sat
#  - constraints+flip
  - constraints+flip+adaptive_eps_step
#  - constraints+flip+adaptive_eps_step+repair