---
config_dir: ./config/
attacks:
  - moeva
#  - pgd
seeds:
  - 42
projects:
  - rq1.botnet.static
eps_list:
  - 1
budgets:
  - 10
loss_evaluations:
  - flip
  - flip+sat
  - constraints+flip
  - constraints+flip+adaptive_eps_step