---
config_dir: ./config/
attacks:
  - moeva
seeds:
  - 42
projects:
  - rq2.botnet.static
eps_list:
  - 4
budgets:
  - 1000
scenari:
#  - project_name: botnet
#    paths:
#      features: ./data/botnet/features_augmented_19_not_mutable.csv
#      constraints: ./data/botnet/constraints.csv
#    reconstruction: True
#    evaluation:
#      project_name: botnet_augmented
#      constraints: ./data/botnet/constraints_augmented_19.csv
  - project_name: botnet_augmented
    paths:
      features: ./data/botnet/features_augmented_19_bis.csv
      constraints: ./data/botnet/constraints_augmented_19_bis.csv
    reconstruction: False
    evaluation:
      project_name: botnet_augmented
      constraints: ./data/botnet/constraints_augmented_19_bis.csv
