---
config_dir: ./config/
models:
  - ./models/botnet/nn_moeva.model
attacks:
  - moeva
#  - pgd
seeds:
  - 42
projects:
  - rq3.botnet.static
eps_list:
  - 1
budgets:
  - 1000
loss_evaluations:
#  - flip
#  - flip+sat
#  - constraints+flip
#  - constraints+flip+adaptive_eps_step