---
project_name: lcld_augmented
paths:
#  model: ./models/botnet/nn.model
#  features: ./data/botnet/features.csv
#  constraints: ./data/botnet/constraints.csv
#  x_candidates: ./data/botnet/x_candidates_common.npy
#  min_max_scaler: ./models/botnet/scaler.joblib
#  ml_scaler: ./models/botnet/scaler.joblib
dirs:
  results: ./out/attacks/lcld/sm_constraints/
misclassification_threshold: 0.25
norm: 2
n_initial_state: 4000
initial_state_offset: 0
system:
  n_jobs: -1
  verbose: 1
save_history: "reduced"
reconstruction: False