---
project_name: lcld_rf
paths:
  model: ./models/lcld_rf/baseline.model
  scaler: ./models/lcld_rf/baseline_scaler.joblib
  x_input: ./data/lcld_rf/baseline_X_test_candidates.npy
  y_input: ./data/lcld_rf/baseline_y_test_candidates.npy
dirs:
  results: ./out/attacks/lcld_rf/rq1/
n_input: -1
input_offset: 0
system:
  n_jobs: 128
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.25
norm: 2
