---
config_dir: ./config/
models:
  - ./models/lcld_rf/adv_moeva.model
attacks:
  - moeva
  - papernot
seeds:
  - 42
projects:
  - lcld_rf/rq2.lcld_rf.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100
