---
config_dir: ./config/
attacks:
  - moeva
seeds:
  - 42
projects:
  - lcld_rf/rq4.lcld_rf.static
  - lcld_rf/rq4.lcld_rf_augmented.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100
