---
projects:
  - lcld_rf
overwrite: False
attack_classes:
  - 1
x_attacks:
 - name: moeva
   path: ./out/attacks/lcld_rf/rq0/x_attacks_moeva_5fc8edb6feb45099f2b31d10b619581f.npy
distance: 0.05
norm: 2
classification_threshold: 0.25