---
config_dir: ./config/
attacks:
  - moeva
  # - pgd
seeds:
  - 42
projects:
  - botnet/rq1.botnet.static
eps_list:
  - 0.2
  - 0.5
  - 1
  - 2
  - 4
budgets:
  - 1000
loss_evaluations:
  - flip
  - flip+sat
  - constraints+flip
  - constraints+flip+adaptive_eps_step
  - constraints+flip+adaptive_eps_step+repair