---
project_name: botnet
paths:
  model: ./models/botnet/baseline.model
  scaler: ./models/botnet/baseline_scaler.joblib
  x_input: ./data/botnet/baseline_X_test_candidates.npy
  y_input: ./data/botnet/baseline_y_test_candidates.npy
dirs:
  results: ./out/attacks/botnet/rq1/
n_input: -1
input_offset: 0
system:
  n_jobs: 100
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.5
norm: 2
