---
config_dir: ./config/
models:
  - ./models/botnet/adv_moeva.model
  - ./models/botnet/adv_moeva_1000.model
  - ./models/botnet/adv_moeva_1000_full.model
attacks:
  - moeva
  - pgd
seeds:
  - 42
projects:
  - url/rq1.url.static
eps_list:
  - 0.2
  - 0.5
  - 1
  - 2
  - 4
budgets:
  - 100
  - 1000
loss_evaluations:
  - constraints+flip+adaptive_eps_step+repair