---
config_dir: ./config/
attacks:
  - moeva
  - pgd
seeds:
  - 42
projects:
  - botnet/rq3.botnet.static
eps_list:
  - 0.2
  - 0.5
  - 1
  - 2
  - 4
budgets:
  - 100
loss_evaluations:
  - constraints+flip+adaptive_eps_step+repair