---
config_dir: ./config/
attacks:
  # - moeva
  - pgd
seeds:
  - 42
projects:
  - lcld/rq0.lcld.static
eps_list:
  - 0.05
budgets:
  - 100
loss_evaluations:
  # - constraints+flip+adaptive_eps_step
  - constraints+flip+adaptive_eps_step+repair
