---
config_dir: ./config/
models:
  - ./models/lcld/adv_moeva.model
  - ./models/lcld/adv_moeva_full.model
  - ./models/lcld/adv_cpgd.model
attacks:
  # - moeva
  - pgd
seeds:
  - 42
projects:
  - lcld/rq2.lcld.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100
loss_evaluations:
  - flip
  - flip+sat
  - constraints+flip
  - constraints+flip+adaptive_eps_step
  - constraints+flip+adaptive_eps_step+repair