---
paths:
  model: ./models/lcld/nn_augmented.model
  x_candidates: ./data/lcld/x_candidates_common_augmented.npy
  min_max_scaler: ./models/lcld/scaler_augmented.joblib
  ml_scaler: ./models/lcld/scaler_augmented.joblib
dirs:
  results: ./out/attacks/lcld/rq2/
misclassification_threshold: 0.25
norm: 2
n_initial_state: 4000
initial_state_offset: 0
system:
  n_jobs: -1
  verbose: 1
save_history: "full"
