---
project_name: lcld_augmented
paths:
  model: ./models/lcld/augmented.model
  scaler: ./models/lcld/augmented_scaler.joblib
  x_input: ./data/lcld_augmented/augmented_X_test_candidates.npy
  y_input: ./data/lcld_augmented/augmented_y_test_candidates.npy
dirs:
  results: ./out/attacks/lcld/rq3/
n_input: -1
input_offset: 0
system:
  n_jobs: 128
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.25
norm: 2
