---
config_dir: ./config/
attacks:
  - moeva
  # - pgd
seeds:
  - 42
projects:
  - lcld/rq3.lcld.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100
loss_evaluations:
  - flip
  - constraints+flip
  - constraints+flip+adaptive_eps_step
  - constraints+flip+adaptive_eps_step+repair