---
project_name: url
paths:
  model: ./models/url/baseline_rf.model
  scaler: ./models/url/baseline_rf_scaler.joblib
  x_input: ./data/url/baseline_X_test_candidates.npy
  y_input: ./data/url/baseline_y_test_candidates.npy
dirs:
  results: ./out/attacks/url/rq1_rf/
n_input: -1
input_offset: 0
system:
  n_jobs: 10
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.5
norm: 2
