---
config_dir: ./config/
models:
  # - ./models/url_rf/adv_moeva_full.model
  - ./models/url_rf/adv_moeva.model
  - ./models/url_rf/adv_papernot.model
attacks:
  - moeva
  - papernot
seeds:
  - 42
projects:
  - url_rf/rq1.url_rf.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100