---
config_dir: ./config/
attacks:
  - moeva
seeds:
  - 42
projects:
  # - url_rf/rq4.url_rf.static
  - url_rf/rq4.url_rf_augmented.static
eps_list:
  - 0.01
  - 0.05
  - 0.1
  - 0.2
budgets:
  - 100
