---
project_name: url_rf_augmented
paths:
  model: ./models/url_rf/adv_moeva_augmented_rq4.model
  scaler: ./models/url_rf/adv_moeva_augmented_rq4_scaler.joblib
  x_input: ./data/url_rf_augmented/augmented_X_test_candidates.npy
  y_input: ./data/url_rf_augmented/augmented_y_test_candidates.npy
dirs:
  results: ./out/attacks/url_rf/rq4/
n_input: -1
input_offset: 0
system:
  n_jobs: 128
  verbose: 1
save_history: "reduced"
reconstruction: False
classification_threshold: 0.5
norm: 2
