---
project_name: lcld
paths:
  model: "./models/lcld/nn.model"
  features: "./data/lcld/features.csv"
  constraints: "./data/lcld/constraints.csv"
  x_candidates: "./data/lcld/x_attack_candidates.npy"
  attack_results: "./out/attacks/lcld/sat/results_eps_0031m.npy"
  objectives: "./out/attacks/lcld/sat/objectives_eps_0031m.csv"
  min_max_scaler: "./models/lcld/scaler.joblib"
  ml_scaler: "./models/lcld/scaler.joblib"
thresholds:
  f1: 0.25
  f2: 0.0001
norm: inf
n_initial_state: 1000
seed: 2020
n_repetition: 1000
initial_state_offset: 0
n_jobs: 14
verbose: 1
